config/routes.rb
Transunion::Application.routes.draw do

  devise_for :members

  match 'finances/customer_payment_bill'            => 'finances#customer_payment_bill',        :as => :customer_payment_bill
  match 'finances/customer_payment_bill/:id/edit'   => 'finances#customer_payment_bill_edit',   :as => :customer_payment_bill_edit
  match 'finances/customer_payment_bill_create'     => 'finances#customer_payment_bill_create', :as => :customer_payment_bill_create
  match 'finances/customer_payment_bill_update/:id' => 'finances#customer_payment_bill_update', :as => :customer_payment_bill_update

  match 'finances/customer_payment_cash'            => 'finances#customer_payment_cash',        :as => :customer_payment_cash
  match 'finances/customer_payment_cash/:id/edit'   => 'finances#customer_payment_cash_edit',   :as => :customer_payment_cash_edit
  match 'finances/customer_payment_cash_create'     => 'finances#customer_payment_cash_create', :as => :customer_payment_cash_create
  match 'finances/customer_payment_cash_update/:id' => 'finances#customer_payment_cash_update', :as => :customer_payment_cash_update

  match 'finances/income_others'            => 'finances#income_others',        :as => :income_others
  match 'finances/income_others/:id/edit'   => 'finances#income_others_edit',   :as => :income_others_edit
  match 'finances/income_others_create'     => 'finances#income_others_create', :as => :income_others_create
  match 'finances/income_others_update/:id' => 'finances#income_others_update', :as => :income_others_update

  match 'finances/carrier_payment_bill'            => 'finances#carrier_payment_bill',        :as => :carrier_payment_bill
  match 'finances/carrier_payment_bill/:id/edit'   => 'finances#carrier_payment_bill_edit',   :as => :carrier_payment_bill_edit
  match 'finances/carrier_payment_bill_create'     => 'finances#carrier_payment_bill_create', :as => :carrier_payment_bill_create
  match 'finances/carrier_payment_bill_update/:id' => 'finances#carrier_payment_bill_update', :as => :carrier_payment_bill_update

  match 'finances/carrier_payment_cash'            => 'finances#carrier_payment_cash',        :as => :carrier_payment_cash
  match 'finances/carrier_payment_cash/:id/edit'   => 'finances#carrier_payment_cash_edit',   :as => :carrier_payment_cash_edit
  match 'finances/carrier_payment_cash_create'     => 'finances#carrier_payment_cash_create', :as => :carrier_payment_cash_create
  match 'finances/carrier_payment_cash_update/:id' => 'finances#carrier_payment_cash_update', :as => :carrier_payment_cash_update

  match 'finances/outcome_others'            => 'finances#outcome_others',        :as => :outcome_others
  match 'finances/outcome_others/:id/edit'   => 'finances#outcome_others_edit',   :as => :outcome_others_edit
  match 'finances/outcome_others_create'     => 'finances#outcome_others_create', :as => :outcome_others_create
  match 'finances/outcome_others_update/:id' => 'finances#outcome_others_update', :as => :outcome_others_update

  match 'finances/outcome_salary'            => 'finances#outcome_salary',        :as => :outcome_salary
  match 'finances/outcome_salary/:id/edit'   => 'finances#outcome_salary_edit',   :as => :outcome_salary_edit
  match 'finances/outcome_salary_create'     => 'finances#outcome_salary_create', :as => :outcome_salary_create
  match 'finances/outcome_salary_update/:id' => 'finances#outcome_salary_update', :as => :outcome_salary_update

  match 'finances/income_cash/:id'     => 'finances#income_cash',     :as => :income_cash
  match 'finances/income_bill/:id'     => 'finances#income_bill',     :as => :income_bill
  match 'finances/outcome_request/:id' => 'finances#outcome_request', :as => :outcome_request

  match 'reports/salary'                     => 'reports#salary_index',            :as => :salary
  match 'reports/salary_colleague_stat/:id'  => 'reports#salary_colleague_stat',   :as => :salary_colleague_stat
  match 'reports/salary_colleague_payed/:id' => 'reports#salary_colleague_payed',  :as => :salary_colleague_payed
  match 'reports/income_for_bill'            => 'reports#income_for_bill',         :as => :income_for_bill

  match 'javascripts/dynamic_drivers' => 'javascripts#dynamic_drivers'

  resources :javascripts

  resources :outcome_sections

  resources :income_sections

  resources :finances

  match 'requests/create_sas' => 'requests#create_sas', :as => :create_sas

  resources :requests

  resources :payment_docs

  resources :payment_ways

  resources :payment_methods

  resources :cargo_classifications

  resources :cars

  resources :car_tonnages

  resources :car_models

  resources :car_types

  resources :customer_companies

  resources :company_faces

  resources :opfs

  resources :users

  root :to =>'index#index', :as => :home

  get "index/index"

  resources :cartypes

  resources :carrier_companies

  resources :drivers

  resources :index

  resources :reports

  match 'signin_form' => 'index#signin_form', :as => :signin_form
  match 'signin'      => 'index#signin'
  match 'signout'     => 'index#signout'

  match 'requests/:id/customer_document' => 'requests#customer_document', :as => :customer_doc
  match 'requests/:id/carrier_document' => 'requests#carrier_document',   :as => :carrier_doc

  match 'requests/:id/save_as' => 'requests#save_as', :as => :save_as

  match '/:controller(/:action(/:id))'

end

app/models/finance.rb
# encoding: UTF-8
class Finance < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 20

  belongs_to :request
  belongs_to :user, :class_name => "User", :foreign_key => "salary_person_id"
end

app/controllers/finances_controller.rb
#encoding: UTF-8
class FinancesController < AuthorizeController

  def index
    @finances = Finance.find(:all, :order => "id DESC")
  end

  #Оплата заказчиком по счёту
  def customer_payment_bill
    @finance = Finance.new
  end

  #Редактирование оплаты заказчиком по счёту
  def customer_payment_bill_edit
    @finance = Finance.find(params[:id])
  end


  #Создание записи оплаты заказчиком по счёту
  def customer_payment_bill_create

    @finance = Finance.new(params[:finance])

    request_one = Request.find(:first, :conditions => "bill_id = #{params[:finance]['bill_id']}")

    if !request_one
      render :action => 'customer_payment_bill', :locals => { :notice => 'Заявки с указанным номером счёта не существует' }
    else
      requests_all = Request.find(:all, :conditions => "bill_id = #{params[:finance]['bill_id']}")
      params[:finance]['glob_type'] = 'income'
      params[:finance]['local_type']  = 'customer_payment_bill'
      params[:finance]['request_id'] = request_one.id

      if request_one.customer_payment_way_for_salary == 'безнал с ндс'
        #do nothing
      else
        requests_all.each do |req|
          req.customer_payment_way_for_salary = 'безнал с ндс'
          req.save
        end
      end

      @finance = Finance.new(params[:finance])
      if @finance.save
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате заказчиком по счету добавлена' })
      else
        render :action => 'customer_payment_bill'
      end
    end
  end

  #Обновление записи оплаты заказчиком по счёту
  def customer_payment_bill_update
    @finance = Finance.find(params[:id])
    request_one = Request.find(:first, :conditions => "bill_id = #{params[:finance][:bill_id]}")

    if !request_one
      render :action => 'customer_payment_bill_edit', :locals => { :notice => 'Заявки с указанным номером счёта не существует' }
    else
      params[:finance][:request_id] = request_one.id
      if @finance.update_attributes(params[:finance])
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате заказчиком по счету добавлена' })
      else
        render :action => 'customer_payment_bill_edit', :locals => { :notice => 'Заявки с указанным номером счёта не существует' }
      end
    end
  end

  #Оплата заказчиком наличными
  def customer_payment_cash
    @finance = Finance.new
  end

  #Редактирование оплаты заказчиком наличными
  def customer_payment_cash_edit
    @finance = Finance.find(params[:id])
  end


  #Создание записи оплаты заказчиком наличными
  def customer_payment_cash_create

    @finance = Finance.new(params[:finance])

    request_one = Request.find(:first, :conditions => "id = #{params[:finance][:request_id]}")

    if !request_one
      render :action => 'customer_payment_cash', :locals => { :notice => 'Заявки с указанным номером не существует' }
    else
      params[:finance]['glob_type'] = 'income'
      params[:finance]['local_type']  = 'customer_payment_cash'
      params[:finance]['request_id'] = request_one.id

      if request_one.customer_payment_way_for_salary == 'безнал с ндс'
        #do nothing
      else
        request_one.customer_payment_way_for_salary = 'наличные'
        requset_one.save
      end

      @finance = Finance.new(params[:finance])
      if @finance.save
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате заказчиком наличными добавлена' })
      else
        render :action => 'customer_payment_cash'
      end
    end
  end

  #Обновление записи оплаты заказчиком наличными
  def customer_payment_cash_update
    @finance = Finance.find(params[:id])
    request_one = Request.find(:first, :conditions => "id = #{params[:finance][:request_id]}")

    if !request_one
      render :action => 'customer_payment_cash_edit', :locals => { :notice => 'Заявки с указанным номером не существует' }
    else
      params[:finance][:request_id] = request_one.id
      if @finance.update_attributes(params[:finance])
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате заказчиком наличными обновлена' })
      else
        render :action => 'customer_payment_cash_edit'
      end
    end
  end

  #Приход прочий
  def income_others
    @finance = Finance.new
  end

  #Редактирование приход прочий
  def income_others_edit
    @finance = Finance.find(params[:id])
  end


  #Создание записи приход прочий
  def income_others_create
    params[:finance]['glob_type'] = 'income'
    params[:finance]['local_type']  = 'income_others'

    @finance = Finance.new(params[:finance])
    if @finance.save
      redirect_to({:action => 'index'}, {:notice => 'Запись о приходе добавлена' })
    else
      render :action => 'income_others'
    end
  end

  #Обновление записи приход прочий
  def income_others_update
    @finance = Finance.find(params[:id])

    if @finance.update_attributes(params[:finance])
      redirect_to({:action => 'index'}, {:notice => 'Запись о приходе обновлена' })
    else
      render :action => 'income_others'
    end
  end

  #Оплата перевозчику по счёту
  def carrier_payment_bill
    @finance = Finance.new
  end

  #Редактирование оплаты перевозчику по счёту
  def carrier_payment_bill_edit
    @finance = Finance.find(params[:id])
  end


  #Создание записи оплаты перевозчиком по счёту
  def carrier_payment_bill_create

    @finance = Finance.new(params[:finance])

    request_one = Request.find(:first, :conditions => "id = #{params[:finance]['request_id']}")

    if !request_one
      render :action => 'carrier_payment_bill', :locals => { :notice => 'Заявки с указанным номером не существует' }
    else
      params[:finance]['glob_type'] = 'outcome'
      params[:finance]['local_type'] = 'carrier_payment_bill'
      params[:finance]['request_id'] = request_one.id

      #Проставление значения поля способа оплаты, для последующего расчёта зарплаты
      if request_one.carrier_payment_way_for_salary == 'наличные'
        #do nothing
      elsif request_one.carrier_payment_way_for_salary == 'безнал с ндс'
        #do nothing
      elsif request_one.carrier_payment_way_for_salary == 'безнал без ндс'
        if params[:finance][:carrier_beznal_way] == 'с ндс'
          request_one.carrier_payment_way_for_salary = 'безнал с ндс'
          request_one.save
        end
      else #если значение не задано
        if params[:finance][:carrier_beznal_way] == 'с ндс'
          request_one.carrier_payment_way_for_salary = 'безнал с ндс'
          request_one.save
        elsif params[:finance][:carrier_beznal_way] == 'без ндс'
          request_one.carrier_payment_way_for_salary = 'безнал без ндс'
          request_one.save
        end
      end

      @finance = Finance.new(params[:finance])
      if @finance.save
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате перевозчику по счету добавлена' })
      else
        render :action => 'carrier_payment_bill'
      end
    end
  end

  #Обновление записи оплаты перевозчиком по счёту
  def carrier_payment_bill_update
    @finance = Finance.find(params[:id])
    request_one = Request.find(:first, :conditions => "id = #{params[:finance][:request_id]}")

    if !request_one
      render :action => 'carrier_payment_bill_edit', :locals => { :notice => 'Заявки с указанным номером счёта не существует' }
    else
      params[:finance][:request_id] = request_one.id
      #Проставление значения поля способа оплаты, для последующего расчёта зарплаты
      if request_one.carrier_payment_way_for_salary == 'наличные'
        #do nothing
      elsif request_one.carrier_payment_way_for_salary == 'безнал с ндс'
        #do nothing
      elsif request_one.carrier_payment_way_for_salary == 'безнал без ндс'
        if params[:finance][:carrier_beznal_way] == 'с ндс'
          request_one.carrier_payment_way_for_salary = 'безнал с ндс'
          request_one.save
        end
      else #если значение не задано
        if params[:finance][:carrier_beznal_way] == 'с ндс'
          request_one.carrier_payment_way_for_salary = 'безнал с ндс'
          request_one.save
        elsif params[:finance][:carrier_beznal_way] == 'без ндс'
          request_one.carrier_payment_way_for_salary = 'безнал без ндс'
          request_one.save
        end
      end
      if @finance.update_attributes(params[:finance])
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате перевозчику по счету добавлена' })
      else
        render :action => 'carrier_payment_bill_edit', :locals => { :notice => 'Заявки с указанным номером счёта не существует' }
      end
    end
  end

  #Оплата перевозчику наличными
  def carrier_payment_cash
    @finance = Finance.new
  end

  #Редактирование оплаты перевозчику наличными
  def carrier_payment_cash_edit
    @finance = Finance.find(params[:id])
  end


  #Создание записи оплаты перевозчику наличными
  def carrier_payment_cash_create

    @finance = Finance.new(params[:finance])

    request_one = Request.find(:first, :conditions => "id = #{params[:finance][:request_id]}")

    if !request_one
      render :action => 'carrier_payment_cash', :locals => { :notice => 'Заявки с указанным номером не существует' }
    else
      params[:finance]['glob_type'] = 'outcome'
      params[:finance]['local_type']  = 'carrier_payment_cash'
      params[:finance]['request_id'] = request_one.id

      if request_one.carrier_payment_way_for_salary == 'безнал с ндс'
        #do nothing
      else
        request_one.carrier_payment_way_for_salary = 'наличные'
        requset_one.save
      end

      @finance = Finance.new(params[:finance])
      if @finance.save
        redirect_to({:action => 'index'}, {:notice => 'Запись об оплате перевозчику  наличными добавлена' })
      else
        render :action => 'carrier_payment_cash'
      end
    end
  end

  #Обновление записи оплаты перевозчику наличными
  def carrier_payment_cash_update
    @finance = Finance.find(params[:id])

app/helpers/finances_helper.rb
#encoding: UTF-8
module FinancesHelper
end

app/views/finances/_carrier_payment_bill_form.html.haml
- content_for(:head) do
  - javascript_include_tag '/javascripts/jquery-datetimeentry/jquery.datetimeentry.js'
- content_for(:head) do
  - stylesheet_link_tag '/javascripts/jquery-datetimeentry/jquery.datetimeentry.css'
- content_for(:head) do
  - javascript_include_tag 'datetime'
- content_for(:head) do
  - javascript_include_tag 'validation'
- args = ( params[:action] == 'carrier_payment_bill' || params[:action] == 'carrier_payment_bill_create' ) ? {:url => carrier_payment_bill_create_path } : {:url => carrier_payment_bill_update_path }
= form_for @finance, args do |f|
  - if @finance.errors.any?
    %div{:style => "width: 450px; margin: 0px auto;", :id => "error_explanation"}
      %h2{:align=>'center'} Чтобы сохранить:
      - if @finance.errors
        - @finance.errors.each do |key,message|
          = message
          %br/
    %br/
  %table
    %tr
      %td{:class => "fieldName fieldInnerTopLeft"} Номер заявки:
      %td{:class => "fieldForm fieldInnerTopRight"}= f.text_field :request_id, :class => "inp required", :size => 3
    %tr
      %td{:class => "fieldName fieldInnerMiddleLeft"} Вид безнала:
      %td{:class => "fieldForm fieldInnerMiddleRight"}= f.select(:carrier_beznal_way, [['с ндс','с ндс'], ['без ндс','без ндс']], {:include_blank => true}, { :class => 'required' })
    %tr
      %td{:class => "fieldName fieldInnerMiddleLeft"} Дата:
      %td{:class => "fieldForm fieldInnerMiddleRight"}= f.text_field :date, :class => "inp required ddateshort", :size => 8
    %tr
      %td{:class => "fieldName fieldInnerBottomLeft"} Сумма:
      %td{:class => "fieldForm fieldInnerBottomRight"}= f.text_field :summ, :class => "inp required", :size => 7
    %tr
      %td{:colspan=>"2", :align=>"center", :class=>"borNone"}= f.submit "Сохранить"

app/views/finances/_customer_payment_bill_form.html.haml
- content_for(:head) do
  - javascript_include_tag '/javascripts/jquery-datetimeentry/jquery.datetimeentry.js'
- content_for(:head) do
  - stylesheet_link_tag '/javascripts/jquery-datetimeentry/jquery.datetimeentry.css'
- content_for(:head) do
  - javascript_include_tag 'datetime'
- content_for(:head) do
  - javascript_include_tag 'validation'
- args = ( params[:action] == 'customer_payment_bill' || params[:action] == 'customer_payment_bill_create' ) ? {:url => customer_payment_bill_create_path } : {:url => customer_payment_bill_update_path }
= form_for @finance, args do |f|
  - if @finance.errors.any?
    %div{:style => "width: 450px; margin: 0px auto;", :id => "error_explanation"}
      %h2{:align=>'center'} Чтобы сохранить:
      - if @finance.errors
        - @finance.errors.each do |key,message|
          = message
          %br/
    %br/
  %table
    %tr
      %td{:class => "fieldName fieldInnerTopLeft"} Номер счёта:
      %td{:class => "fieldForm fieldInnerTopRight"}= f.text_field :bill_id, :class => "inp required", :size => 3
    %tr
      %td{:class => "fieldName fieldInnerMiddleLeft"} Дата:
      %td{:class => "fieldForm fieldInnerMiddleRight"}= f.text_field :date, :class => "inp required ddateshort", :size => 8
    %tr
      %td{:class => "fieldName fieldInnerBottomLeft"} Сумма:
      %td{:class => "fieldForm fieldInnerBottomRight"}= f.text_field :summ, :class => "inp required", :size => 7
    %tr
      %td{:colspan=>"2", :align=>"center", :class=>"borNone"}= f.submit "Сохранить"

app/views/finances/index.html.haml
= link_to image_tag("income_transp_nal_button.jpg"), customer_payment_cash_path, :class => 'financeAdd'
= link_to image_tag("income_trans_beznal_button.jpg", :border=>0), customer_payment_bill_path, :class => 'financeAdd'
= link_to image_tag("income_other_button.jpg", :border=>0), income_others_path, :class => 'financeAdd'
= link_to image_tag("outcome_trans_nal_button.jpg", :border=>0), carrier_payment_cash_path, :class => 'financeAdd', :style => 'margin-left:100px;'
= link_to image_tag("outcome_trans_beznal_button.jpg", :border=>0), carrier_payment_bill_path, :class => 'financeAdd'
= link_to image_tag("outcome_colleagues_button.jpg", :border=>0), outcome_salary_path, :class => 'financeAdd'
= link_to image_tag("outcome_other_button.jpg", :border=>0), outcome_others_path, :class => 'financeAdd'
%br/
%br/
%table
  %tr
    %td{:class => 'borNone', :colspan => '3', :align => 'center'}
      %span{:style => 'font-size: 20px; font-style: bold;'}
        != "Касса <b>#{Time.now.strftime('%d.%m.%Y %H:%M')}</b>"
  %tr
    %td{:style => 'background:#c4f8da;'}= "Приход наличных: #{income_cash_all} руб"
    %td{:style => 'background:#EEE8AA;'}!= "Наличных в кассе: <b>#{income_cash_all - outcome_cash_all}</b> руб"
    %td{:style => 'background:#f8ccca;'}= "Расход наличных: #{outcome_cash_all} руб"
%br/
%table
  %tr
    %th{:class => "th1 bold", :rowspan => '2'}Приход<br/>/<br/>Расход
    %th{:class => "th1 bold", :rowspan => '2'}Дата
    %th{:class => "th1 bold", :rowspan => '2'}Тип
    %th{:class => "th1 bold", :rowspan => '2'}Заявка №
    %th{:class => "th1 bold", :rowspan => '2'}Счёт №
    %th{:class => "th1 bold", :rowspan => '2'}Компания
    %th{:class => "th1 bold", :colspan => '3', :style => 'border-bottom:medium none;'}Сумма
    %th{:class => "th1 bold", :colspan => '2', :style => 'border-bottom:medium none;'}Сотрудник
    %th{:class => "th1 bold", :rowspan => '2'}
    %th{:class => "th1 bold", :rowspan => '2'}
  %tr
    %th{:class => 'th2'}К оплате
    %th{:class => 'th2'}Оплачено
    %th{:class => 'th2'}Остаток
    %th{:class => 'th2'}ФИО
    %th{:class => 'th2'}Должность
  - @finances.each do |fin|
    %tr
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =fin.glob_type == 'income' ? 'приход' : 'расход'
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =fin.date.strftime('%d-%m-%Y')
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; 'перев/безнал'; end;
        =if fin.local_type == 'carrier_payment_cash'; 'перев/нал'; end;
        =if fin.local_type == 'customer_payment_bill'; 'заказч/безнал'; end;
        =if fin.local_type == 'customer_payment_cash'; 'заказч/нал'; end;
        =if fin.local_type == 'outcome_others'; 'расх/проч'; end;
        =if fin.local_type == 'income_others'; 'прих/проч'; end;
        =if fin.local_type == 'outcome_salary'; 'зарплата'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; fin.request_id; end;
        =if fin.local_type == 'carrier_payment_cash'; fin.request_id ; end;
        =if fin.local_type == 'customer_payment_bill'; '------------'; end;
        =if fin.local_type == 'customer_payment_cash'; fin.request_id ; end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; '------------'; end;
        =if fin.local_type == 'carrier_payment_cash'; '------------' ; end;
        =if fin.local_type == 'customer_payment_bill'; fin.bill_id; end;
        =if fin.local_type == 'customer_payment_cash'; '------------' ; end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; fin.request.carrier_company.name; end;
        =if fin.local_type == 'carrier_payment_cash'; fin.request.carrier_company.name ; end;
        =if fin.local_type == 'customer_payment_bill'; fin.request.customer_company.name; end;
        =if fin.local_type == 'customer_payment_cash'; fin.request.customer_company.name ; end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; fin.request.carrier_summ_to_pay; end;
        =if fin.local_type == 'carrier_payment_cash'; fin.request.carrier_summ_to_pay ; end;
        =if fin.local_type == 'customer_payment_bill'; customer_summ_to_pay_for_bill(fin.bill_id); end;
        =if fin.local_type == 'customer_payment_cash'; fin.request.customer_summ_to_pay ; end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =fin.summ
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; finance_balance(fin); end;
        =if fin.local_type == 'carrier_payment_cash'; finance_balance(fin); end;
        =if fin.local_type == 'customer_payment_bill'; finance_balance(fin); end;
        =if fin.local_type == 'customer_payment_cash'; finance_balance(fin) ; end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =fin.local_type == 'outcome_salary' ? fin.user.full_name : '------------'
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =fin.local_type == 'outcome_salary' ? fin.user.position : '------------'
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; link_to 'открыть', outcome_request_path(fin); end;
        =if fin.local_type == 'carrier_payment_cash'; link_to 'открыть', outcome_request_path(fin); end;
        =if fin.local_type == 'customer_payment_bill'; link_to 'открыть', income_bill_path(fin); end;
        =if fin.local_type == 'customer_payment_cash'; link_to 'открыть', income_cash_path(fin); end;
        =if fin.local_type == 'outcome_others'; '------------'; end;
        =if fin.local_type == 'income_others'; '------------'; end;
        =if fin.local_type == 'outcome_salary'; '------------'; end;
      %td{:class => 'th3', :id => fin.glob_type == 'income' ? 'income' : 'outcome' }
        =if fin.local_type == 'carrier_payment_bill'; '------'; end;
        =if fin.local_type == 'carrier_payment_cash'; '------' ; end;
        =if fin.local_type == 'customer_payment_bill'; '------'; end;
        =if fin.local_type == 'customer_payment_cash'; '------' ; end;
        =if fin.local_type == 'outcome_others'; link_to 'изменить', outcome_others_edit_path(fin); end;
        =if fin.local_type == 'income_others'; link_to 'изменить', income_others_edit_path(fin); end;
        =if fin.local_type == 'outcome_salary'; link_to 'изменить', outcome_salary_edit_path(fin); end;