config/routes.rb
Transunion::Application.routes.draw do

  devise_for :members

  match 'finances/customer_payment_bill'            => 'finances#customer_payment_bill',        :as => :customer_payment_bill
  match 'finances/customer_payment_bill/:id/edit'   => 'finances#customer_payment_bill_edit',   :as => :customer_payment_bill_edit
  match 'finances/customer_payment_bill_create'     => 'finances#customer_payment_bill_create', :as => :customer_payment_bill_create
  match 'finances/customer_payment_bill_update/:id' => 'finances#customer_payment_bill_update', :as => :customer_payment_bill_update

  match 'finances/customer_payment_cash'            => 'finances#customer_payment_cash',        :as => :customer_payment_cash
  match 'finances/customer_payment_cash/:id/edit'   => 'finances#customer_payment_cash_edit',   :as => :customer_payment_cash_edit
  match 'finances/customer_payment_cash_create'     => 'finances#customer_payment_cash_create', :as => :customer_payment_cash_create
  match 'finances/customer_payment_cash_update/:id' => 'finances#customer_payment_cash_update', :as => :customer_payment_cash_update

  match 'finances/income_others'            => 'finances#income_others',        :as => :income_others
  match 'finances/income_others/:id/edit'   => 'finances#income_others_edit',   :as => :income_others_edit
  match 'finances/income_others_create'     => 'finances#income_others_create', :as => :income_others_create
  match 'finances/income_others_update/:id' => 'finances#income_others_update', :as => :income_others_update

  match 'finances/carrier_payment_bill'            => 'finances#carrier_payment_bill',        :as => :carrier_payment_bill
  match 'finances/carrier_payment_bill/:id/edit'   => 'finances#carrier_payment_bill_edit',   :as => :carrier_payment_bill_edit
  match 'finances/carrier_payment_bill_create'     => 'finances#carrier_payment_bill_create', :as => :carrier_payment_bill_create
  match 'finances/carrier_payment_bill_update/:id' => 'finances#carrier_payment_bill_update', :as => :carrier_payment_bill_update

  match 'finances/carrier_payment_cash'            => 'finances#carrier_payment_cash',        :as => :carrier_payment_cash
  match 'finances/carrier_payment_cash/:id/edit'   => 'finances#carrier_payment_cash_edit',   :as => :carrier_payment_cash_edit
  match 'finances/carrier_payment_cash_create'     => 'finances#carrier_payment_cash_create', :as => :carrier_payment_cash_create
  match 'finances/carrier_payment_cash_update/:id' => 'finances#carrier_payment_cash_update', :as => :carrier_payment_cash_update

  match 'finances/outcome_others'            => 'finances#outcome_others',        :as => :outcome_others
  match 'finances/outcome_others/:id/edit'   => 'finances#outcome_others_edit',   :as => :outcome_others_edit
  match 'finances/outcome_others_create'     => 'finances#outcome_others_create', :as => :outcome_others_create
  match 'finances/outcome_others_update/:id' => 'finances#outcome_others_update', :as => :outcome_others_update

  match 'finances/outcome_salary'            => 'finances#outcome_salary',        :as => :outcome_salary
  match 'finances/outcome_salary/:id/edit'   => 'finances#outcome_salary_edit',   :as => :outcome_salary_edit
  match 'finances/outcome_salary_create'     => 'finances#outcome_salary_create', :as => :outcome_salary_create
  match 'finances/outcome_salary_update/:id' => 'finances#outcome_salary_update', :as => :outcome_salary_update

  match 'finances/income_cash/:id'     => 'finances#income_cash',     :as => :income_cash
  match 'finances/income_bill/:id'     => 'finances#income_bill',     :as => :income_bill
  match 'finances/outcome_request/:id' => 'finances#outcome_request', :as => :outcome_request

  match 'reports/salary'                     => 'reports#salary_index',            :as => :salary
  match 'reports/salary_colleague_stat/:id'  => 'reports#salary_colleague_stat',   :as => :salary_colleague_stat
  match 'reports/salary_colleague_payed/:id' => 'reports#salary_colleague_payed',  :as => :salary_colleague_payed
  match 'reports/income_for_bill'            => 'reports#income_for_bill',         :as => :income_for_bill

  match 'javascripts/dynamic_drivers' => 'javascripts#dynamic_drivers'

  resources :javascripts

  resources :outcome_sections

  resources :income_sections

  resources :finances

  match 'requests/create_sas' => 'requests#create_sas', :as => :create_sas

  resources :requests

  resources :payment_docs

  resources :payment_ways

  resources :payment_methods

  resources :cargo_classifications

  resources :cars

  resources :car_tonnages

  resources :car_models

  resources :car_types

  resources :customer_companies

  resources :company_faces

  resources :opfs

  resources :users

  root :to =>'index#index', :as => :home

  get "index/index"

  resources :cartypes

  resources :carrier_companies

  resources :drivers

  resources :index

  resources :reports

  match 'signin_form' => 'index#signin_form', :as => :signin_form
  match 'signin'      => 'index#signin'
  match 'signout'     => 'index#signout'

  match 'requests/:id/customer_document' => 'requests#customer_document', :as => :customer_doc
  match 'requests/:id/carrier_document' => 'requests#carrier_document',   :as => :carrier_doc

  match 'requests/:id/save_as' => 'requests#save_as', :as => :save_as

  match '/:controller(/:action(/:id))'

end

app/models/payment_method.rb
# encoding: UTF-8
class PaymentMethod < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 20
end

app/controllers/payment_methods_controller.rb
# encoding: UTF-8
class PaymentMethodsController < AuthorizeController
  # GET /payment_methods
  def index
    @payment_methods = PaymentMethod.paginate :page => params[:page], :order => 'id DESC'
  end

  # GET /payment_methods/1
  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  # POST /payment_methods
  def create
    @payment_method = PaymentMethod.new(params[:payment_method])

    if @payment_method.save
      redirect_to({:action => 'index'}, {:notice => 'Вид расчёта добавлен'})
    else
      render :action => "new"
    end
  end

  # PUT /payment_methods/1
  def update
    @payment_method = PaymentMethod.find(params[:id])

    if @payment_method.update_attributes(params[:payment_method])
      redirect_to(@payment_method, :notice => 'Изменения внесены')
    else
      render :action => "edit"
    end
  end

  # DELETE /payment_methods/1
  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy

    redirect_to(payment_methods_url)
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.haml
= form_for @payment_method do |f|
  -if @payment_method.errors.any?
    %div{:style => "width: 450px; margin: 0px auto;", :id => "error_explanation"}
      %h2{:align=>'center'} Чтобы сохранить:
      - @payment_method.errors.each do |key,message|
        = message
        %br/
    %br/

  %table
    %tr
      %td{:class => 'fieldName fieldBothLeft'} Вид расчёта:
      %td{:class => 'fieldForm fieldBothRight'}= f.text_field :payment_method, :class => 'inp'
    -# Не показывать кнопку сохранить для просмотра карточки
    - if !(params[:action] == 'show')
      %tr
        %td{:colspan=>'2', :align=>'center', :class=>'borNone'}= f.submit 'Сохранить'

app/views/payment_methods/edit.html.haml
%h1{ :class => "tableTitle", :style => "width: 400px; margin: 0px auto; color:red" } Изменение вида расчёта
%br/
= render 'form'

app/views/payment_methods/index.html.haml
%div{:style => 'width: 180px; margin: 0px auto;'}
  = link_to image_tag("add_payment_method_button.jpg", :border=>0), new_payment_method_path, :class => 'editLink', :id => 'addPayment_methodLink', :style => 'width: 300px; margin: 0px auto;'
%table
  %tr
    %th.th1 №
    %th.th1 Вид расчёта
    %th.th1 Открыть

  - @payment_methods.each do |payment_method|
    %tr{ :class => cycle('odd','even') }
      %td.th3= payment_method.id
      %td.th3= payment_method.payment_method
      %td.th3= link_to 'Открыть', payment_method, :id => "showPayment_methodLink"

%br
%div{ :style => 'width: 10%; margin: 0px auto;' }
  = will_paginate(@payment_method, :previous_label => '&#8592;', :next_label => '&#8594;')

app/views/payment_methods/new.html.haml
%h1{ :class => "tableTitle", :style => "width: 400px; margin: 0px auto; color:red"} Добавление вида расчёта
%br
= render 'form'

app/views/payment_methods/show.html.haml
%h1{:class => "tableTitle", :style => "width: 550px; margin: 0px auto; color:red;"} Просмотр карточки вида расчёта
%br/
- content_for(:head) do
  = javascript_include_tag 'disableForms'
%br/
= render 'form'
%br/
%br/

%div{:style =>"width: 600px; margin: 0px auto;"}
  = link_to image_tag("editButton.jpg"), edit_payment_method_path(@payment_method), :id => 'editPayment_methodLink'
  = link_to image_tag("deleteButton.jpg"), @payment_method, :confirm => 'Вы уверены', :id => 'deletePayment_methodLink', :method => :delete
%br/
%div{:style => "width: 200px; margin: 0px auto;"}
  = link_to 'к списку видов расчёта', payment_methods_path