config/routes.rb
Transunion::Application.routes.draw do

  devise_for :members

  match 'finances/customer_payment_bill'            => 'finances#customer_payment_bill',        :as => :customer_payment_bill
  match 'finances/customer_payment_bill/:id/edit'   => 'finances#customer_payment_bill_edit',   :as => :customer_payment_bill_edit
  match 'finances/customer_payment_bill_create'     => 'finances#customer_payment_bill_create', :as => :customer_payment_bill_create
  match 'finances/customer_payment_bill_update/:id' => 'finances#customer_payment_bill_update', :as => :customer_payment_bill_update

  match 'finances/customer_payment_cash'            => 'finances#customer_payment_cash',        :as => :customer_payment_cash
  match 'finances/customer_payment_cash/:id/edit'   => 'finances#customer_payment_cash_edit',   :as => :customer_payment_cash_edit
  match 'finances/customer_payment_cash_create'     => 'finances#customer_payment_cash_create', :as => :customer_payment_cash_create
  match 'finances/customer_payment_cash_update/:id' => 'finances#customer_payment_cash_update', :as => :customer_payment_cash_update

  match 'finances/income_others'            => 'finances#income_others',        :as => :income_others
  match 'finances/income_others/:id/edit'   => 'finances#income_others_edit',   :as => :income_others_edit
  match 'finances/income_others_create'     => 'finances#income_others_create', :as => :income_others_create
  match 'finances/income_others_update/:id' => 'finances#income_others_update', :as => :income_others_update

  match 'finances/carrier_payment_bill'            => 'finances#carrier_payment_bill',        :as => :carrier_payment_bill
  match 'finances/carrier_payment_bill/:id/edit'   => 'finances#carrier_payment_bill_edit',   :as => :carrier_payment_bill_edit
  match 'finances/carrier_payment_bill_create'     => 'finances#carrier_payment_bill_create', :as => :carrier_payment_bill_create
  match 'finances/carrier_payment_bill_update/:id' => 'finances#carrier_payment_bill_update', :as => :carrier_payment_bill_update

  match 'finances/carrier_payment_cash'            => 'finances#carrier_payment_cash',        :as => :carrier_payment_cash
  match 'finances/carrier_payment_cash/:id/edit'   => 'finances#carrier_payment_cash_edit',   :as => :carrier_payment_cash_edit
  match 'finances/carrier_payment_cash_create'     => 'finances#carrier_payment_cash_create', :as => :carrier_payment_cash_create
  match 'finances/carrier_payment_cash_update/:id' => 'finances#carrier_payment_cash_update', :as => :carrier_payment_cash_update

  match 'finances/outcome_others'            => 'finances#outcome_others',        :as => :outcome_others
  match 'finances/outcome_others/:id/edit'   => 'finances#outcome_others_edit',   :as => :outcome_others_edit
  match 'finances/outcome_others_create'     => 'finances#outcome_others_create', :as => :outcome_others_create
  match 'finances/outcome_others_update/:id' => 'finances#outcome_others_update', :as => :outcome_others_update

  match 'finances/outcome_salary'            => 'finances#outcome_salary',        :as => :outcome_salary
  match 'finances/outcome_salary/:id/edit'   => 'finances#outcome_salary_edit',   :as => :outcome_salary_edit
  match 'finances/outcome_salary_create'     => 'finances#outcome_salary_create', :as => :outcome_salary_create
  match 'finances/outcome_salary_update/:id' => 'finances#outcome_salary_update', :as => :outcome_salary_update

  match 'finances/income_cash/:id'     => 'finances#income_cash',     :as => :income_cash
  match 'finances/income_bill/:id'     => 'finances#income_bill',     :as => :income_bill
  match 'finances/outcome_request/:id' => 'finances#outcome_request', :as => :outcome_request

  match 'reports/salary'                     => 'reports#salary_index',            :as => :salary
  match 'reports/salary_colleague_stat/:id'  => 'reports#salary_colleague_stat',   :as => :salary_colleague_stat
  match 'reports/salary_colleague_payed/:id' => 'reports#salary_colleague_payed',  :as => :salary_colleague_payed
  match 'reports/income_for_bill'            => 'reports#income_for_bill',         :as => :income_for_bill

  match 'javascripts/dynamic_drivers' => 'javascripts#dynamic_drivers'

  resources :javascripts

  resources :outcome_sections

  resources :income_sections

  resources :finances

  match 'requests/create_sas' => 'requests#create_sas', :as => :create_sas

  resources :requests

  resources :payment_docs

  resources :payment_ways

  resources :payment_methods

  resources :cargo_classifications

  resources :cars

  resources :car_tonnages

  resources :car_models

  resources :car_types

  resources :customer_companies

  resources :company_faces

  resources :opfs

  resources :users

  root :to =>'index#index', :as => :home

  get "index/index"

  resources :cartypes

  resources :carrier_companies

  resources :drivers

  resources :index

  resources :reports

  match 'signin_form' => 'index#signin_form', :as => :signin_form
  match 'signin'      => 'index#signin'
  match 'signout'     => 'index#signout'

  match 'requests/:id/customer_document' => 'requests#customer_document', :as => :customer_doc
  match 'requests/:id/carrier_document' => 'requests#carrier_document',   :as => :carrier_doc

  match 'requests/:id/save_as' => 'requests#save_as', :as => :save_as

  match '/:controller(/:action(/:id))'

end

app/models/cargo_classification.rb
# encoding: UTF-8
class CargoClassification < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 20
end

app/controllers/cargo_classifications_controller.rb
# encoding: UTF-8
class CargoClassificationsController < AuthorizeController
  # GET /cargo_classifications
  def index
    @cargo_classifications = CargoClassification.paginate :page => params[:page], :order => 'id DESC'
  end

  # GET /cargo_classifications/1
  def show
    @cargo_classification = CargoClassification.find(params[:id])
  end

  # GET /cargo_classifications/new
  def new
    @cargo_classification = CargoClassification.new
  end

  # GET /cargo_classifications/1/edit
  def edit
    @cargo_classification = CargoClassification.find(params[:id])
  end

  # POST /cargo_classifications
  def create
    @cargo_classification = CargoClassification.new(params[:cargo_classification])

    if @cargo_classification.save
      redirect_to({:action => 'index'}, {:notice => 'Классификация груза добавлена'})
    else
      render :action => "new"
    end
  end

  # PUT /cargo_classifications/1
  def update
    @cargo_classification = CargoClassification.find(params[:id])

    if @cargo_classification.update_attributes(params[:cargo_classification])
      redirect_to(@cargo_classification, :notice => 'Изменения внесены')
    else
      render :action => "edit"
    end
  end

  # DELETE /cargo_classifications/1
  def destroy
    @cargo_classification = CargoClassification.find(params[:id])
    @cargo_classification.destroy

    redirect_to(cargo_classifications_url)
  end
end

app/helpers/cargo_classifications_helper.rb
module CargoClassificationsHelper
end

app/views/cargo_classifications/_form.html.haml
= form_for @cargo_classification do |f|
  -if @cargo_classification.errors.any?
    %div{:style => "width: 450px; margin: 0px auto;", :id => "error_explanation"}
      %h2{:align=>'center'} Чтобы сохранить:
      - @cargo_classification.errors.each do |key,message| 
        = message
        %br/
    %br/

  %table
    %tr
      %td{:class => 'fieldName fieldBothLeft'} Классификация груза:
      %td{:class => 'fieldForm fieldBothRight'}= f.text_field :classification, :class => 'inp'
    -# Не показывать кнопку сохранить для просмотра карточки
    - if !(params[:action] == 'show')
      %tr
        %td{:colspan=>'2', :align=>'center', :class=>'borNone'}= f.submit 'Сохранить'

app/views/cargo_classifications/edit.html.haml
%h1{ :class => "tableTitle", :style => "width: 550px; margin: 0px auto; color:red" } Изменение классификации груза
%br/
= render 'form'

app/views/cargo_classifications/index.html.haml
%div{:style => 'width: 270px; margin: 0px auto;'}
  = link_to image_tag("add_cargo_classification_button.jpg", :border=>0), new_cargo_classification_path, :class => 'editLink', :id => 'addCargo_classificationLink', :style => 'width: 300px; margin: 0px auto;'
%table
  %tr
    %th.th1 №
    %th.th1 Классификация груза
    %th.th1 Открыть

  - @cargo_classifications.each do |cargo_classification|
    %tr{ :class => cycle('odd','even') }
      %td.th3= cargo_classification.id
      %td.th3= cargo_classification.classification
      %td.th3= link_to 'Открыть', cargo_classification, :id => "showCargo_classificationLink"

%br
%div{ :style => 'width: 10%; margin: 0px auto;' }
  = will_paginate(@cargo_classification, :previous_label => '&#8592;', :next_label => '&#8594;')

app/views/cargo_classifications/new.html.haml
%h1{ :class => "tableTitle", :style => "width: 550px; margin: 0px auto; color:red"} Добавление классификации груза
%br
= render 'form'

app/views/cargo_classifications/show.html.haml
%h1{:class => "tableTitle", :style => "width: 650px; margin: 0px auto; color:red;"} Просмотр карточки классификации груза
%br/
- content_for(:head) do
  = javascript_include_tag 'disableForms'
%br/
= render 'form'
%br/
%br/

%div{:style =>"width: 600px; margin: 0px auto;"}
  = link_to image_tag("editButton.jpg"), edit_cargo_classification_path(@cargo_classification), :id => 'editCargo_classificationLink'
  = link_to image_tag("deleteButton.jpg"), @cargo_classification, :confirm => 'Вы уверены', :id => 'deleteCargo_classificationLink', :method => :delete
%br/
%div{:style => "width: 250px; margin: 0px auto;"}
  = link_to 'к списку классификаций груза', cargo_classifications_path