config/routes.rb
Transunion::Application.routes.draw do

  devise_for :members

  match 'finances/customer_payment_bill'            => 'finances#customer_payment_bill',        :as => :customer_payment_bill
  match 'finances/customer_payment_bill/:id/edit'   => 'finances#customer_payment_bill_edit',   :as => :customer_payment_bill_edit
  match 'finances/customer_payment_bill_create'     => 'finances#customer_payment_bill_create', :as => :customer_payment_bill_create
  match 'finances/customer_payment_bill_update/:id' => 'finances#customer_payment_bill_update', :as => :customer_payment_bill_update

  match 'finances/customer_payment_cash'            => 'finances#customer_payment_cash',        :as => :customer_payment_cash
  match 'finances/customer_payment_cash/:id/edit'   => 'finances#customer_payment_cash_edit',   :as => :customer_payment_cash_edit
  match 'finances/customer_payment_cash_create'     => 'finances#customer_payment_cash_create', :as => :customer_payment_cash_create
  match 'finances/customer_payment_cash_update/:id' => 'finances#customer_payment_cash_update', :as => :customer_payment_cash_update

  match 'finances/income_others'            => 'finances#income_others',        :as => :income_others
  match 'finances/income_others/:id/edit'   => 'finances#income_others_edit',   :as => :income_others_edit
  match 'finances/income_others_create'     => 'finances#income_others_create', :as => :income_others_create
  match 'finances/income_others_update/:id' => 'finances#income_others_update', :as => :income_others_update

  match 'finances/carrier_payment_bill'            => 'finances#carrier_payment_bill',        :as => :carrier_payment_bill
  match 'finances/carrier_payment_bill/:id/edit'   => 'finances#carrier_payment_bill_edit',   :as => :carrier_payment_bill_edit
  match 'finances/carrier_payment_bill_create'     => 'finances#carrier_payment_bill_create', :as => :carrier_payment_bill_create
  match 'finances/carrier_payment_bill_update/:id' => 'finances#carrier_payment_bill_update', :as => :carrier_payment_bill_update

  match 'finances/carrier_payment_cash'            => 'finances#carrier_payment_cash',        :as => :carrier_payment_cash
  match 'finances/carrier_payment_cash/:id/edit'   => 'finances#carrier_payment_cash_edit',   :as => :carrier_payment_cash_edit
  match 'finances/carrier_payment_cash_create'     => 'finances#carrier_payment_cash_create', :as => :carrier_payment_cash_create
  match 'finances/carrier_payment_cash_update/:id' => 'finances#carrier_payment_cash_update', :as => :carrier_payment_cash_update

  match 'finances/outcome_others'            => 'finances#outcome_others',        :as => :outcome_others
  match 'finances/outcome_others/:id/edit'   => 'finances#outcome_others_edit',   :as => :outcome_others_edit
  match 'finances/outcome_others_create'     => 'finances#outcome_others_create', :as => :outcome_others_create
  match 'finances/outcome_others_update/:id' => 'finances#outcome_others_update', :as => :outcome_others_update

  match 'finances/outcome_salary'            => 'finances#outcome_salary',        :as => :outcome_salary
  match 'finances/outcome_salary/:id/edit'   => 'finances#outcome_salary_edit',   :as => :outcome_salary_edit
  match 'finances/outcome_salary_create'     => 'finances#outcome_salary_create', :as => :outcome_salary_create
  match 'finances/outcome_salary_update/:id' => 'finances#outcome_salary_update', :as => :outcome_salary_update

  match 'finances/income_cash/:id'     => 'finances#income_cash',     :as => :income_cash
  match 'finances/income_bill/:id'     => 'finances#income_bill',     :as => :income_bill
  match 'finances/outcome_request/:id' => 'finances#outcome_request', :as => :outcome_request

  match 'reports/salary'                     => 'reports#salary_index',            :as => :salary
  match 'reports/salary_colleague_stat/:id'  => 'reports#salary_colleague_stat',   :as => :salary_colleague_stat
  match 'reports/salary_colleague_payed/:id' => 'reports#salary_colleague_payed',  :as => :salary_colleague_payed
  match 'reports/income_for_bill'            => 'reports#income_for_bill',         :as => :income_for_bill

  match 'javascripts/dynamic_drivers' => 'javascripts#dynamic_drivers'

  resources :javascripts

  resources :outcome_sections

  resources :income_sections

  resources :finances

  match 'requests/create_sas' => 'requests#create_sas', :as => :create_sas

  resources :requests

  resources :payment_docs

  resources :payment_ways

  resources :payment_methods

  resources :cargo_classifications

  resources :cars

  resources :car_tonnages

  resources :car_models

  resources :car_types

  resources :customer_companies

  resources :company_faces

  resources :opfs

  resources :users

  root :to =>'index#index', :as => :home

  get "index/index"

  resources :cartypes

  resources :carrier_companies

  resources :drivers

  resources :index

  resources :reports

  match 'signin_form' => 'index#signin_form', :as => :signin_form
  match 'signin'      => 'index#signin'
  match 'signout'     => 'index#signout'

  match 'requests/:id/customer_document' => 'requests#customer_document', :as => :customer_doc
  match 'requests/:id/carrier_document' => 'requests#carrier_document',   :as => :carrier_doc

  match 'requests/:id/save_as' => 'requests#save_as', :as => :save_as

  match '/:controller(/:action(/:id))'

end

app/models/customer_company.rb
# encoding: UTF-8
class CustomerCompany < ActiveRecord::Base

  cattr_accessor :params

  before_validation :standartise_fields

  cattr_reader :per_page
  @@per_page = 20
  has_many    :requests
  belongs_to  :opf
  belongs_to  :company_face

  validates :title,           :presence => { :message => "Укажите название компании" }
  validates :opf_id,          :presence => { :message => "Укажите ОПФ компании" }
  validates :operates_basis,  :presence => { :message => "Заполните поле 'Действует на основании'" }
  validates :company_face_id, :presence => { :message => "Заполните поле 'Компания в лице'" }
  validates :manager_name,    :presence => { :message => "Укажите ФИО управляющего" }
  validates :legal_address,   :presence => { :message => "Укажите юридический адрес" }
  validates :actual_address,  :presence => { :message => "Укажите фактический адрес" }
  validates :phone,           :presence => { :message => "Укажите телефон" }

  validates_numericality_of :respons_refuse_loading_day
  validates_numericality_of :respons_idle_excessively_hours
  validates_numericality_of :respons_idle_excessively_percent
  validates_numericality_of :respons_payment_late

  validates_numericality_of :respons_undeliver_transport_loading
  validates_numericality_of :respons_transport_late_loading_hours
  validates_numericality_of :respons_transport_late_loading_percent
  validates_numericality_of :respons_transport_late_destination_hours
  validates_numericality_of :respons_transport_late_destination_percent
  validates_numericality_of :respons_document_late

  def name
    "#{self.opf.opf} #{self.title}"
  end

  def standartise_fields
    #Проверка на случай если данные идут не из формы, а из fixtures
    if params
      self.respons_refuse_loading_day                  = params[:respons_refuse_loading_day].to_s.gsub(/,/,'.')
      self.respons_idle_excessively_hours              = params[:respons_idle_excessively_hours].to_s.gsub(/,/,'.')
      self.respons_idle_excessively_percent            = params[:respons_idle_excessively_percent].to_s.gsub(/,/,'.')
      self.respons_payment_late                        = params[:respons_payment_late].to_s.gsub(/,/,'.')
      self.respons_undeliver_transport_loading         = params[:respons_undeliver_transport_loading].to_s.gsub(/,/,'.')
      self.respons_transport_late_loading_hours        = params[:respons_transport_late_loading_hours].to_s.gsub(/,/,'.')
      self.respons_transport_late_loading_percent      = params[:respons_transport_late_loading_percent].to_s.gsub(/,/,'.')
      self.respons_transport_late_destination_hours    = params[:respons_transport_late_destination_hours].to_s.gsub(/,/,'.')
      self.respons_transport_late_destination_percent  = params[:respons_transport_late_destination_percent].to_s.gsub(/,/,'.')
      self.respons_document_late                       = params[:respons_document_late].to_s.gsub(/,/,'.')
    end
  end

end

app/controllers/customer_companies_controller.rb
# encoding: UTF-8
class CustomerCompaniesController < AuthorizeController
  before_filter do
    #Передача params в модель
    CustomerCompany.params = params[:customer_company]
  end

  # GET /customer_companies
  def index
    @customer_companies = CustomerCompany.paginate :page => params[:page], :order => 'id DESC'
  end

  # GET /customer_companies/1
  def show
    @customer_company = CustomerCompany.find(params[:id])
  end

  # GET /customer_companies/new
  def new
    @customer_company = CustomerCompany.new
  end

  # GET /customer_companies/1/edit
  def edit
    @customer_company = CustomerCompany.find(params[:id])
  end

  # POST /customer_companies
  def create
    @customer_company = CustomerCompany.new(params[:customer_company])

    if @customer_company.save
      redirect_to({:action => 'index'}, {:notice => 'Компания заказчик добавлена'})
    else
      render :action => "new"
    end
  end

  # PUT /customer_companies/1
  def update
    @customer_company = CustomerCompany.find(params[:id])

    if @customer_company.update_attributes(params[:customer_company])
      redirect_to(@customer_company, :notice => 'Изменения внесены')
    else
      render :action => "edit"
    end
  end

  # DELETE /customer_companies/1
  def destroy
    @customer_company = CustomerCompany.find(params[:id])
    @customer_company.destroy

    redirect_to(customer_companies_url)
  end

end

app/helpers/customer_companies_helper.rb
module CustomerCompaniesHelper
end

app/views/customer_companies/_form.html.haml
- content_for(:head) do
  - javascript_include_tag 'hide_show'

= form_for @customer_company do |f|
  -if @customer_company.errors.any?
    %div{:style => "width: 450px; margin: 0px auto;", :id => "error_explanation"}
      %h2{:align=>'center'} Чтобы сохранить:
      - @customer_company.errors.each do |key,message|
        = message
        %br/
    %br/

  %table
    %tr
      %td{:class => 'fieldName fieldInnerTopLeft'} Название компании:
      %td{:class => 'fieldForm fieldInnerTopRight'}= f.text_field :title, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} ОПФ:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.collection_select :opf_id, Opf.find(:all), :id, :opf, { :include_blank => true },
          { :class => 'inp required' }
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Действует на основании:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :operates_basis, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Компания в лице:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.collection_select :company_face_id, CompanyFace.find(:all), :id, :company_face, { :include_blank => true },
        { :class => 'inp required' }
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} ФИО управляющего:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :manager_name, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Юридический адрес:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :legal_address, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Фактический адрес:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :actual_address, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} ОГРН:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :ogrn, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} ОКПО:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :okpo, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} ИНН:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :inn, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} КПП:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :kpp, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Телефон:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :phone, :class => 'inp required'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Факс:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :fax, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Email:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :email, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Расчетный счет:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :current_account, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Банк:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :bank, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Банковский ИНН:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :bank_inn, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} Корреспондентский счет:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :correspondent_account, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerMiddleLeft'} БИК:
      %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :bik, :class => 'inp'
    %tr
      %td{:class => 'fieldName fieldInnerBottomLeft'} Черный список:
      %td{:class => 'fieldForm fieldInnerBottomRight'}= f.check_box :black_label, :class => 'inp'
    %tr
      %td{:class => 'borNone', :align => 'center', :colspan => '2'} <br />
    %tr
      %td{:class => 'borNone', :id => 'responsibilityButton',
                               :align => 'center', :style => 'color:blue; text-decoration:underline; cursor:pointer',
                               :colspan=>'2'} Ответственность сторон
    %tr
      %td{:class => 'borNone', :align => 'center', :colspan => '2'} <br />
    %tbody{:id => 'responsibility', :style => 'display:none'}
      %tr
        %td{:class => 'title borNone', :align => 'center', :colspan => '2'} Ответственность сторон (текст Договора-заявки)
      %tr
        %td{:class => 'borNone', :align => 'center', :colspan=> '2'}!= "<span style = 'font-size:16px;font-style:italic;text-decoration:underline;'> Ответственность Транс-Юнион:</span>"
      %tr
        %td{:class => 'fieldName fieldInnerTopLeft'} Штраф за отказ от ТС в день погрузки:
        %td{:class => 'fieldForm fieldInnerTopRight'}!= "в размере  #{f.text_field :respons_refuse_loading_day, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '20' : @customer_company.respons_refuse_loading_day } % от стоимости перевозки."
      %tr
        %td{:class => 'fieldName fieldInnerMiddleLeft'}!= "Штраф за простой ТС более: #{f.text_field :respons_idle_excessively_hours, :size => '5', :class=>'inp', :value => params[:action] == 'new' ? '2' : @customer_company.respons_idle_excessively_hours} часов"
        %td{:class => 'fieldForm fieldInnerMiddleRight'}!= "в размере #{f.text_field :respons_idle_excessively_percent, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '5' : @customer_company.respons_idle_excessively_percent} % от стоимости перевозки за каждый час простоя."
      %tr
        %td{:class => 'fieldName fieldInnerBottomLeft'} Штраф за просрочку оплаты счетов:
        %td{:class => 'fieldForm fieldInnerBottomRight'}!= "в размере #{f.text_field :respons_payment_late, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '2' : @customer_company.respons_payment_late} % от суммы просроченного платежа за каждый день просрочки."
      %tr
        %td{:class => 'borNone', :align => 'center', :colspan => '2'}!= "<span style='font-size: 16px; font-style: italic; text-decoration: underline;'>Ответственность перевозчика:</span>"
      %tr
        %td{:class => 'fieldName fieldInnerTopLeft'} Требования по замене ТС:
        %td{:class => 'fieldForm fieldInnerTopRight'}= f.text_field :respons_transport_replacement_req, :class => 'inp', :size => 80, :id =>'resp',
          :value => params[:action] == 'new' ? 'в случае поломки или аварии ТС в пути следования предоставить взамен равноценное исправное ТС своими силами не позднее 24 часов с момента неисправности ТС и за свой счет.' : @customer_company.respons_transport_replacement_req
      %tr
        %td{:class => 'fieldName fieldInnerMiddleLeft'} Возмещение ущерба:
        %td{:class => 'fieldForm fieldInnerMiddleRight'}= f.text_field :respons_compensation_for_damage, :class => 'inp', :size => 80, :id => 'resp',
          :value => params[:action] == 'new' ? 'в случае повреждения, недостачи, утраты груза – в размере пропорциональном стоимости повреждённого,  недостающего, утраченного  груза согласно ТТН.' : @customer_company.respons_compensation_for_damage
      %tr
        %td{:class => 'fieldName fieldInnerMiddleLeft'} Штраф за неподачу ТС под погрузку:
        %td{:class => 'fieldForm fieldInnerMiddleRight'}!= "в размере #{f.text_field :respons_undeliver_transport_loading, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '10' : @customer_company.respons_undeliver_transport_loading } % от стоимости перевозки."
      %tr
        %td{:class => 'fieldName fieldInnerMiddleLeft'}!= "Штраф за опоздание ТС под погрузку более: #{f.text_field :respons_transport_late_loading_hours, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '2' : @customer_company.respons_transport_late_loading_hours } часов"
        %td{:class => 'fieldForm fieldInnerMiddleRight'}!= "в размере #{f.text_field :respons_transport_late_loading_percent, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '5' : @customer_company.respons_transport_late_loading_percent } % от стоимости перевозки за каждый час опоздания."
      %tr
        %td{:class => 'fieldName fieldInnerMiddleLeft'}!= "Штраф за просрочку доставки груза более: #{f.text_field :respons_transport_late_destination_hours, :class => 'inp', :size=>'5', :value => params[:action] == 'new' ? '4' : @customer_company.respons_transport_late_destination_hours } часов"
        %td{:class => 'fieldForm fieldInnerMiddleRight'}!= "в размере #{f.text_field :respons_transport_late_destination_percent, :class => 'inp', :size => '5', :value => params[:action] == 'new' ? '5' : @customer_company.respons_transport_late_destination_percent } % от стоимости перевозки за каждый час просрочки."
      %tr
        %td{:class => 'fieldName fieldInnerBottomLeft'} Штраф за несвоевременное возвращение документов:
        %td{:class => 'fieldForm fieldInnerBottomRight'}!= "в размере #{f.text_field :respons_document_late, :class => 'inp', :size=>'5', :value => params[:action] == 'new' ? '0.5' : @customer_company.respons_document_late} % от стоимости перевозки за каждый день просрочки"
    -# Не показывать кнопку сохранить для просмотра карточки
    - if !(params[:action] == 'show')
      %tr
        %td{:colspan=>'2', :align=>'center', :class=>'borNone'}= f.submit 'Сохранить'

app/views/customer_companies/edit.html.haml
%h1{ :class => "tableTitle", :style => "width: 500px; margin: 0px auto; color:red" } Изменение компании заказчика
%br/
= render 'form'

app/views/customer_companies/index.html.haml
%div{:style => 'width: 270px; margin: 0px auto;'}
  = link_to image_tag("add_customer_company_button.jpg", :border=>0), new_customer_company_path, :class => 'editLink', :id => 'addCustomer_companyLink', :style => 'width: 300px; margin: 0px auto;'
%table
  %tr
    %th.th1 №
    %th.th1 Название
    %th.th1 Фактический адрес
    %th.th1 Телефон
    %th.th1 Открыть

  - @customer_companies.each do |customer_company|
    %tr{ :class => cycle('odd','even') }
      %td.th3= customer_company.id
      %td.th3= customer_company.title
      %td.th3= customer_company.actual_address
      %td.th3= customer_company.phone
      %td.th3= link_to 'Открыть', customer_company, :id => "showCustomer_companyLink"

%br
%div{ :style => 'width: 10%; margin: 0px auto;' }
  = will_paginate(@customer_company, :previous_label => '&#8592;', :next_label => '&#8594;')

app/views/customer_companies/new.html.haml
%h1{ :class => "tableTitle", :style => "width: 530px; margin: 0px auto; color:red"} Добавление компании заказчика
%br
= render 'form'

app/views/customer_companies/show.html.haml
%h1{:class => "tableTitle", :style => "width: 650px; margin: 0px auto; color:red;"} Просмотр карточки компании заказчика
%br/
- content_for(:head) do
  = javascript_include_tag 'disableForms'
%br/
= render 'form'
%br/
%br/

%div{:style =>"width: 600px; margin: 0px auto;"}
  = link_to image_tag("editButton.jpg"), edit_customer_company_path(@customer_company), :id => 'editCustomer_companyLink'
  = link_to image_tag("deleteButton.jpg"), @customer_company, :confirm => 'Вы уверены', :id => 'deleteCustomer_companyLink', :method => :delete
%br/
%div{:style => "width: 300px; margin: 0px auto;"}
  = link_to 'к списку компаний заказчиков', customer_companies_path